# Generated by Django 3.0.3 on 2020-03-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('CU', 'Customer'), ('MA', 'Manager'), ('DI', 'Distributor')], default='CU', max_length=2)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ('city', 'l_name', 'f_name', 'status'),
            },
        ),
    ]
