# Generated by Django 3.0.4 on 2020-03-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('country', 'name', 'status', 'category', 'issue')},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='HR', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='issue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('C', 'Converter'), ('E', 'Enduser'), ('D', 'Distributor'), ('A', 'Agent')], default='C', max_length=1),
        ),
    ]
