# Generated by Django 3.0.4 on 2020-03-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(choices=[('TE', 'Treofan'), ('JE', 'Jindal Europe'), ('JI', 'Jindal India'), ('JA', 'Jindal America')], default='JE', max_length=2)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('group', models.CharField(choices=[('NPD', 'NPD'), ('SPP', 'Specialty Packaging'), ('SPL', 'Specialty Commodity'), ('IML', 'IML')], default='NPD', max_length=3)),
                ('family', models.CharField(choices=[('UW', 'Uncoated White'), ('CW', 'Coated White'), ('UT', 'Uncoated Transparent'), ('CT', 'Coated transparent'), ('MT', 'Metallised'), ('ST', 'SealTough'), ('AL', 'Alox'), ('HD', 'EthyLyte')], default='UW', max_length=2)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
                'ordering': ('name', 'family'),
            },
        ),
    ]
