# Generated by Django 3.0.4 on 2020-03-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200328_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('NPD', 'NPD'), ('SPP', 'Specialty Packaging'), ('SPL', 'Specialty Labeling'), ('IML', 'IML'), ('COM', 'Commodity')], default='NPD', max_length=3),
        ),
    ]
