# Generated by Django 3.0.4 on 2020-04-10 22:24

from django.db import migrations, models
import django.db.models.deletion
import purchase.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200328_2146'),
        ('product', '0004_auto_20200328_1932'),
        ('purchase', '0004_auto_20200305_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='FOC ordered', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'stage',
            },
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('front_partner', '-quantity', 'product'), 'verbose_name_plural': 'purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ('stage',), 'verbose_name_plural': 'PurchaseItems'},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='note',
            new_name='application',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='purchase',
            name='RND',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='back_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_partner_projects', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='deadline',
            field=models.DateField(default=purchase.models.six_month_from_today),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='front_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_partner_projects', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_projects', to='product.Product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='replacing',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='structure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='comment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_is_going', to='purchase.Purchase'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projs_on_stage', to='purchase.Stage'),
        ),
    ]
