# Generated by Django 3.0.3 on 2020-03-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_cc', models.PositiveSmallIntegerField(choices=[(42, '42%'), (40, '40%'), (30, '30%'), (20, '20%'), (10, '10%'), (0, '0%')], default=0)),
                ('discount_ci', models.PositiveSmallIntegerField(choices=[(40, '40%'), (30, '30%'), (20, '20%'), (10, '10%'), (0, '0%')], default=0)),
                ('delivery', models.CharField(choices=[('HD', 'To Hand'), ('CD', 'Cash on Delivery Post'), ('PO', 'No Cash Post')], default='HD', max_length=2)),
                ('money_received', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_sales', to='customer.Customer')),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'db_table': 'sell',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sells', to='product.Product')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_items', to='sell.Sell')),
            ],
            options={
                'verbose_name_plural': 'SellItems',
                'db_table': 'sellitem',
                'ordering': ('-sell',),
            },
        ),
    ]
