# Generated by Django 3.0.4 on 2020-04-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200328_2146'),
        ('sell', '0005_auto_20200327_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ('converter', '-updated_at'), 'verbose_name_plural': 'sales'},
        ),
        migrations.AlterModelOptions(
            name='sellitem',
            options={'ordering': ('-quantity',), 'verbose_name_plural': 'SellItems'},
        ),
        migrations.RemoveField(
            model_name='sell',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='discount_cc',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='discount_ci',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='money_received',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='note',
        ),
        migrations.AddField(
            model_name='sell',
            name='converter',
            field=models.ForeignKey(limit_choices_to=models.Q(('status', 'C'), ('status', 'D'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converter_sales', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='sellitem',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sellitem',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellitem',
            name='enduser',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'E'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enduser_sales', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
