# Generated by Django 3.0.4 on 2020-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_auto_20200410_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
